final Map formatUpsertPoktanBKB = {
    "mengetahuiTempat": "",
    "mengetahuiTanggal": "",
    "mengetahuiKetuaNama": "",
    "mengetahuiPembinaNama": "",
    "loginName": null,
    "status": "",
    "statusDate": "",
    "created": "",
    "createdBy": "",
    "lastModified": "", //DateTime utc ISO string
    "lastModifiedBy": "",
    "id": "",
    "provinsiId": 0,
    "kabupatenId": 0,
    "kecamatanId": 0,
    "kelurahanId": 0,
    "rwId": 0,
    "rtId": 0,
    "kodePoktan": "",
    "nomorRegister": "",
    "namaKelompok": "",
    "alamatJalan": "",
    "pembinaPKBID": "",
    "namaPembinaPKBID": "",
    "jabatanPembinaId": "",
    "jabatanPembinaLainnya": null,
    "skPengukuhanAda": "",
    "nomorSK": "",
    "tanggalSK": "",
    "skDikeluarkanOlehId": "",
    "sumberDanaAPBN": "",
    "sumberDanaAPBD": "",
    "sumberDanaADD": "",
    "sumberDanaSWADAYA": "",
    "sumberDanaMITRA": "",
    "keterpaduanKelompokPOSYANDU": "",
    "keterpaduanKelompokPAUD": "",
    "keterpaduanKelompokLAINNYA": "",
    "akunMedsos": "",
    "namaMedsos": "",
    "statusKampungKB": "",
    "materi1": "",
    "materi2": "",
    "materi3": "",
    "materi4": "",
    "materi5": "",
    "materi6": "",
    "materi7": "",
    "materi8": "",
    "materi9": "",
    "materi10": "",
    "materiLainnya": "",
    "materiLainnyaDeskripsi": null,
    "saranaBKBKit": "",
    "saranaBKBKitStunting": "",
    "saranaKartuKembangAnak": "",
    "saranaLainnya": "",
    "saranaLainnyaDeskripsi": null,
    "pengurusKelompok": [
        {
            "nomorUrut": "1",
            "nomor": 1,
            "nik": "",
            "nama": "",
            "nomorHp": null,
            "kki": "",
            "jabatan": "1",
            "pelatihan": "7",
            "pelatihanMenjadiOrangTuaHebat": "0",
            "pelatihanBKBHI": null,
            "pelatihanPengasuhan1000HPK": null,
            "pelatihanBKBEmas": null,
            "pelatihanPecatatanPelaporan": null,
            "pelatihanLainnya": null,
            "belumDilatih": "1",
            "jabatanPengurusKetua": "1",
            "jabatanPengurusSekretaris": "0",
            "jabatanPengurusBendahara": "0",
            "jabatanPengurusKaderUmur0sd1Tahun": "0",
            "jabatanPengurusKaderUmur1sd2Tahun": "0",
            "jabatanPengurusKaderUmur2sd3Tahun": "0",
            "jabatanPengurusKaderUmur3sd4Tahun": "0",
            "jabatanPengurusKaderUmur4sd5Tahun": "0",
            "jabatanPengurusKaderUmur5sd6Tahun": "0",
            "flag": null,
        },
    ],
    "anggotaKelompok": [
        {
            "id": null,
            "nomorUrut": null,
            "kki": null,
            "nik": null,
            "namaAnggota": null,
            "nomorHp": null,
            "statusAnggota": "1",
            "created": null,
            "createdBy": null,
            "lastModified": null,
            "lastModifiedBy": null,
            "flag": null,
            "namaAnak": null,
            "tanggalLahirAnak": null,
            "bbLahirAnak": null,
            "pbLahirAnak": null,
            "nomor": null,
        },
        {
            "nomorUrut": null,
            "nomor": null,
            "nik": null,
            "namaAnggota": null,
            "nomorHp": null,
            "nikAnggota": null,
            "namaAnak": null,
            "pbLahirAnak": null,
            "bbLahirAnak": null,
            "kki": null,
            "noKeluarga": null,
            "tanggalLahirAnak": null,
            "BKBID": null,
            "statusAnggota": "1",
            "flag": "Upsert",
        },
    ],
};

final Map formatUpsertPoktanBKL = {
    "mengetahuiTempat": "",
    "mengetahuiTanggal": "",
    "mengetahuiKetuaNama": "",
    "mengetahuiPembinaNama": "",
    "loginName": "",
    "status": "",
    "statusDate": "",
    "id": "",
    "provinsiId": 0,
    "kabupatenId": 0,
    "kecamatanId": 0,
    "kelurahanId": 0,
    "rwId": 0,
    "rtId": 0,
    "kodePoktan": "",
    "nomorRegister": "",
    "namaKelompok": "",
    "alamatJalan": "",
    "pembinaPKBID": "",
    "namaPembinaPKBID": "",
    "jabatanPembinaId": "",
    "jabatanPembinaLainnya": null,
    "akunMedsos": "",
    "namaMedsos": null,
    "skPengukuhanAda": "",
    "nomorSK": null,
    "tanggalSK": "",
    "skDikeluarkanOlehId": null,
    "sumberDanaAPBN": "",
    "sumberDanaAPBD": "",
    "sumberDanaADD": "",
    "sumberDanaDAK": null,
    "sumberDanaSWADAYA": "",
    "sumberDanaMITRA": "",
    "keterpaduanKelompokPOSYANDU": "",
    "keterpaduanKelompokPUSAKA": null,
    "keterpaduanKelompokEkonomi": "",
    "keterpaduanKelompokLAINNYA": "",
    "keterpaduanKelompokTIDAK": null,
    "statusProPN": "",
    "tanggalProPN": "",
    "coEBKL": "",
    "coEBKL_sk": null,
    "coEBKL_nomorSk": null,
    "coEBKL_tanggalSk": "",
    "statusKampungKB": "",
    "disableProPN": "",
    "bukuMateri1": "",
    "bukuMateri2": "",
    "bukuMateri3": "",
    "bukuMateri4": "",
    "bukuMateri5": "",
    "bukuMateri6": "",
    "bukuMateri7": "",
    "bukuMateri8": "",
    "bukuMateri9": "",
    "bukuMateri10": "",
    "sarana1": "",
    "sarana2": "",
    "sarana3": "",
    "sarana4": "",
    "sarana5": "",
    "sarana6": "",
    "saranaLainnya": "",
    "bukuMateriLainnyaDeskripsi": "",
    "saranaLainnyaDeskripsi": "",
    "pengurusKelompok": [
        {
            "nomorUrut": "",
            "nomor": 0,
            "nik": "",
            "nama": "",
            "nomorHp": "-",
            "kki": "",
            "jabatan": "",
            "pelatihan": "",
            "jabatanPengurusKetua": 0,
            "jabatanPengurusSekretaris": 0,
            "jabatanPengurusBendahara":0,
            "jabatanPengurusKader":0,
            "pelatihan7DimensiLansiaTangguh": "",
            "pelatihanKelanjutanUsiaLainnya": null,
            "pelatihanPendampinganPJP": null,
            "belumDilatih": "",
            "pelatihan_tbl": "",
            "jabatan_tbl": "",
            "flag": null
        }
    ],
    "anggotaKelompok":[
        {
            "id": null,
            "nomorUrut": "",
            "kki": "",
            "nik": "",
            "namaAnggota": "",
            "nomorHp": "-",
            "statusAnggota": "",
            "created": null,
            "createdBy": null,
            "lastModified": null,
            "lastModifiedBy": null,
            "flag": null,
            "jumlahLansiaMandiri": null,
            "jumlahLansiaPJP": null,
            "statusLansia": "",
            "tingkatKemandirian": "",
            "nomorBKL": ""
        },
        {
            "nomorUrut": 0,
            "nomor": 0,
            "nomorBKL": "",
            "nik": "",
            "namaAnggota": "",
            "nomorHp": "-",
            "statusLansia": "",
            "tingkatKemandirian": "",
            "kki":"",
            "noKeluarga": "",
            "statusLansia_tbl": "",
            "tingkatKemandirian_tbl": "",
            "flag": "Upsert"
        }
    ]
};