name: Flutter Release Build

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Flutter APK & Windows Installer
    runs-on: windows-latest

    env:
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          cache: true
      
      - name: Install specific NDK version
        run: |
          yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" "ndk;27.0.12077973"

      - name: Set NDK environment variable
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/27.0.12077973" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/27.0.12077973" >> $GITHUB_ENV

      - name: Cache Gradle & Android build
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Install dependencies
        run: flutter pub get

      - name: Create .env file
        shell: bash
        run: |
          echo "SUPABASE_PROJ=${{ secrets.SUPABASE_PROJ }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
          echo "KEYSTORE_FILE=${{ secrets.KEYSTORE_FILE }}" >> .env
          echo "STORE_PASSWORD=${{ secrets.STORE_PASSWORD }}" >> .env
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> .env
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> .env

      - name: Decode and decrypt keystore zip
        shell: bash
        run: |
          echo "${{ secrets.KEYSTORE_ZIP }}" | base64 -d > keystore.zip.gpg
          gpg --batch --yes --passphrase "${{ secrets.STORE_PASSWORD }}" --output keystore.zip --decrypt keystore.zip.gpg
          unzip -o keystore.zip -d android/app

      - name: Get app version
        id: version
        shell: bash
        run: |
          VERSION=$(grep '^version: .*+.*' pubspec.yaml | sed -E 's/version: ([^+]+)\+.*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build APK (split per ABI)
        run: flutter build apk --release --split-per-abi --dart-define-from-file=.env

      - name: Rename APKs
        shell: bash
        run: |
          mkdir renamed-apks
          for file in build/app/outputs/flutter-apk/app-*-release.apk; do
            abi=$(basename "$file" | cut -d'-' -f2)
            mv "$file" "renamed-apks/SigaAutomator-${{ steps.version.outputs.version }}_${abi}.apk"
          done

      - name: Upload Android APKs
        uses: actions/upload-artifact@v4
        with:
          name: SigaAutomator-${{ steps.version.outputs.version }}-android
          path: renamed-apks

      - name: Build Windows App
        run: flutter build windows --release --dart-define-from-file=.env

      - name: Modify .iss with version and output dir
        shell: bash
        run: |
          sed -i 's/^AppVersion=.*/AppVersion=${{ steps.version.outputs.version }}/' build_tools/pack_windows.iss
          sed -i 's|^OutputDir=.*|OutputDir="..\\windows-installer"|' build_tools/pack_windows.iss
          sed -i 's/^OutputBaseFilename=.*/OutputBaseFilename=SigaAutomator-${{ steps.version.outputs.version }}_win_64/' build_tools/pack_windows.iss
          sed -i 's|^Source: .*|Source: "..\\build\\windows\\x64\\runner\\Release\\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs|' build_tools/pack_windows.iss

      - name: Install Inno Setup
        run: choco install innosetup --no-progress

      - name: Create Windows Installer with Inno Setup
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" build_tools\pack_windows.iss

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: SigaAutomator-${{ steps.version.outputs.version }}-windows
          path: windows-installer/*.exe

      - name: Generate Changelog from Git Commits
        id: changelog
        if: github.ref == 'refs/heads/main'
        run: |
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: SigaAutomator v${{ steps.version.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: |
            renamed-apks/*.apk
            windows-installer/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
